#!/usr/bin/env kotlinr

/**
 * Regenerates the 'style > ForbiddenSuppress > rules' list for every active rule
 * and alias. ForbiddenSuppress compares suppression strings literally, so each
 * blocked spelling must be listed. Run this after enabling or disabling a rule.
 *
 * Usage:
 *   ./tools/generate-forbidden-suppress.main.kts [path/to/detekt.yml]
 */

import java.nio.file.Path
import kotlin.io.path.Path
import kotlin.io.path.readLines
import kotlin.io.path.writeText
import kotlin.system.exitProcess

val configPath: Path = Path(args.firstOrNull() ?: "detekt.yml")
val lines = runCatching { configPath.readLines() }.getOrElse {
    System.err.println("Cannot read $configPath: ${it.message}")
    exitProcess(1)
}

val sectionPattern = Regex("""^([a-z][a-z-]*):\s*$""")
val rulePattern = Regex("""^ {2}([A-Za-z]+):\s*$""")
val quotedPattern = Regex("""'([^']+)'""")

data class Id(
    val section: String,
    val name: String,
)

val ids = buildList {
    var section = ""
    var rule: String? = null
    var active: Boolean? = null
    for (line in lines) {
        sectionPattern.find(line)?.let {
            section = it.groupValues[1]
            rule = null
            return@let
        }
        rulePattern.find(line)?.let {
            rule = it.groupValues[1]
            active = null
            return@let
        }
        val name = rule ?: continue
        when {
            line.startsWith("    active: true") -> {
                active = true
                add(Id(section, name))
            }
            line.startsWith("    active: false") -> active = false
            active == true && line.trimStart().startsWith("aliases:") ->
                quotedPattern.findAll(line).forEach { add(Id(section, it.groupValues[1])) }
        }
    }
}

if (ids.isEmpty()) {
    System.err.println("No active rules found in $configPath. Is it a detekt config?")
    exitProcess(1)
}

// Verified against detekt 2.0.0-alpha.6: every one of these silences a rule,
// while an unknown prefix such as 'nonsense:ReturnCount' does not.
val separators = listOf(":", ".")

// Doubly qualified forms also silence rules, but including them exceeds detekt's
// YAML size limit. README documents the remaining escape hatch.
fun formsOf(id: Id) = buildList {
    add(id.name)
    for (separator in separators) {
        add("detekt$separator${id.name}")
        add("${id.section}$separator${id.name}")
    }
}

val sections = ids
    .map { it.section }
    .distinct()

val names = buildSet {
    ids.forEach { addAll(formsOf(it)) }
    // The rule set name on its own silences every rule in it.
    sections.forEach { section ->
        add(section)
        separators.forEach { add("detekt$it$section") }
    }
}.sorted()

val marker = "  ForbiddenSuppress:"
val start = lines.indexOfFirst { it == marker }
if (start < 0) {
    System.err.println("No '$marker' block in $configPath")
    exitProcess(1)
}
val rulesAt = (start until lines.size).firstOrNull { lines[it].startsWith("    rules:") } ?: run {
    System.err.println("The ForbiddenSuppress block in $configPath has no 'rules:' key")
    exitProcess(1)
}
var end = rulesAt + 1
while (end < lines.size && lines[end].startsWith("      - ")) {
    end++
}

val rendered = buildList {
    addAll(lines.subList(0, rulesAt))
    add("    rules: # HEAPY: generated by tools/generate-forbidden-suppress.main.kts, do not edit by hand")
    names.forEach { add("      - '$it'") }
    addAll(lines.subList(end, lines.size))
}

val text = rendered.joinToString("\n")

// snakeyaml, which detekt parses the config with, refuses a larger document and
// the run dies with a stack trace that says nothing about this list.
val yamlLimit = 102_400
val size = text.codePointCount(0, text.length)
if (size > yamlLimit) {
    System.err.println("The result is $size code points, over the $yamlLimit YAML limit detekt enforces.")
    System.err.println("Drop a form from formsOf() or the config will not parse. Nothing was written.")
    exitProcess(1)
}

configPath.writeText(text)
println("Wrote ${names.size} entries from ${ids.size} ids across ${sections.size} rule sets to $configPath")
println("$configPath is now $size of $yamlLimit code points")
